name: Выпуск

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Ветка выпуска'
        required: true
        default: 'beta'
        type: choice
        options:
          - 'beta'
          - 'release'
  pull_request:
    paths:
      - 'ru-ru/**'
  push:
    paths:
      - 'ru-ru/**'

env:
  REPO_NAME: ${{ github.repository }}
  BASE_DIR: ru-ru

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Установка ветки выпуска
        id: set-release-type
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "release_type=beta" >> $GITHUB_ENV
            echo "Event: Push to main branch. Set release_type to beta."
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "release_type=${{ github.event.inputs.release_type }}" >> $GITHUB_ENV
            echo "Event: Workflow dispatch. Set release_type to ${{ github.event.inputs.release_type }}."
          else
            echo "release_type=release" >> $GITHUB_ENV
            echo "Event: Other. Set release_type to release."
          fi

      - name: Определение существующих тегов
        id: determine-tags
        run: |
          tags=$(git tag --list)
          
          if [[ "${{ env.release_type }}" == "beta" ]]; then
            prefix="B"
            last_tag=$(echo "$tags" | grep "^$prefix" | sed "s/^$prefix//" | sort -V | tail -n 1)
          else
            last_tag=$(echo "$tags" | grep -E "^[0-9]+$" | sort -V | tail -n 1)
          fi

          if [ -z "$last_tag" ]; then
            next_tag="1"
          else
            next_tag="$(($last_tag + 1))"
          fi

          echo "next_tag=$next_tag" >> $GITHUB_ENV
          echo "Следующий тег определён: $next_tag"

      - name: Проверка существующего выпуска с таким тегом
        id: check-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ env.release_type }}" == "beta" ]]; then
            tag="B${{ env.next_tag }}"
          else
            tag="${{ env.next_tag }}"
          fi

          echo "Проверка существования релиза с тегом: $tag"
          release_exists=$(gh release view "$tag" --json tagName --jq '.tagName' || echo "not_found")
          
          if [[ "$release_exists" != "not_found" ]]; then
            echo "Релиз с тегом $release_exists уже существует. Увеличиваем тег."
            next_tag="$(( ${{ env.next_tag }} + 1 ))"
            echo "next_tag=$next_tag" >> $GITHUB_ENV
          else
            echo "Релиз с тегом $tag не найден."
          fi

      - name: Дополнительная проверка существования после увеличения тега
        if: env.next_tag != ${{ env.next_tag }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ env.release_type }}" == "beta" ]]; then
            tag="B${{ env.next_tag }}"
          else
            tag="${{ env.next_tag }}"
          fi

          echo "Повторная проверка релиза с тегом: $tag"
          release_exists=$(gh release view "$tag" --json tagName --jq '.tagName' || echo "not_found")
          
          if [[ "$release_exists" != "not_found" ]]; then
            echo "Релиз с тегом $release_exists уже существует. Увеличиваем тег снова."
            next_tag="$(( ${{ env.next_tag }} + 1 ))"
            echo "next_tag=$next_tag" >> $GITHUB_ENV
          else
            echo "Релиз с тегом $tag не найден после увеличения."
          fi

      - name: Архивация ru-ru
        run: |
          if [[ "${{ env.release_type }}" == "beta" ]]; then
            archive_name="Fusion-2.5-Russian-Language-B${{ env.next_tag }}.zip"
          else
            archive_name="Fusion-2.5-Russian-Language-${{ env.next_tag }}.zip"
          fi
          echo "Создание архива: $archive_name"
          zip -r "$archive_name" "$BASE_DIR"

      - name: Создание выпуска
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.release_type == 'beta' && 'B' || '' }}${{ env.next_tag }}
          files: Fusion-2.5-Russian-Language-${{ env.release_type == 'beta' && 'B' || '' }}${{ env.next_tag }}.zip
          name: "${{ env.next_tag }}-й ${{ env.release_type == 'beta' && 'бета-' || '' }}выпуск"
          body: "Автоматический ${{ env.release_type == 'beta' && 'бета-' || '' }}выпуск."
          prerelease: ${{ env.release_type == 'beta' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}