name: Выпуск

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Ветка выпуска'
        required: true
        default: 'beta'
        type: choice
        options:
          - 'beta'
          - 'release'
  pull_request:
    paths:
      - 'ru-ru/**'
  push:
    paths:
      - 'ru-ru/**'

env:
  REPO_NAME: ${{ github.repository }}
  BASE_DIR: ru-ru

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка ветки выпуска
        if: github.event_name == 'workflow_dispatch'
        run: echo "release_type=${{ github.event.inputs.release_type }}" >> $GITHUB_ENV

      - name: Определение существующих тегов
        id: tags
        run: |
          tags=$(git tag --list)
          if [[ "${{ env.release_type }}" == "beta" ]]; then
            prefix="B"
            last_tag=$(echo "$tags" | grep "^$prefix" | sed "s/^$prefix//" | sort -Vr | head -n 1)
          else
            last_tag=$(echo "$tags" | grep -E "^[0-9]+$" | sort -Vr | head -n 1)
          fi

          if [ -z "$last_tag" ]; then
            next_tag="1"
          else
            next_tag="$(($last_tag + 1))"
          fi

          echo "next_tag=$next_tag" >> $GITHUB_ENV

      - name: Архивация ru-ru
        run: |
          zip -r Fusion-2.5-Russian-Language-${{ env.next_tag }}.zip $BASE_DIR

      - name: Создание выпуска
        uses: softprops/action-gh-release@v2
        with:
          tag_name: |
            ${{ env.release_type == 'beta' && 'B' || '' }}${{ env.next_tag }}
          files: Fusion-2.5-Russian-Language-${{ env.next_tag }}.zip
          name: |
            ${{ env.next_tag }}-й ${{ env.release_type == 'beta' && 'бета-' || '' }}выпуск
          body: |
            Автоматический ${{ env.release_type == 'beta' && 'бета-' || '' }}выпуск.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}